name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: problem
    attributes:
      label: What problem would this feature solve?
      description: Describe the problem or limitation you are facing. You can attach screenshots, if you have any.
      placeholder: Tell us what is missing!
      value: "I have a problem that could be solved by a new feature!"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you would like
      description: A clear and concise description of what you want to happen.
      placeholder: Tell us what you want!
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you have considered
      description: A clear and concise description of any alternative solutions or features you have considered.
      placeholder: Tell us what else you tried!
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: checkboxes
    id: checks
    attributes:
      label: Sanity Checks
      description: Please check all that apply. If you haven't done these, please do them before submitting the issue.
      options:
        - label: I am running a version of the software that is still supported (not EOL).
          required: true
        - label: I searched for existing issues (open or closed) and did not find a duplicate.
          required: true
        - label: I made sure not to disclose any sensitive information in this issue description or in any attached logs / screenshots.
          required: true
